services:
  - type: web
    name: autobuddy-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python render_start.py
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URL
        sync: false
      - key: FEATURE_DATABASE_URL
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: 475485627719-lgd8c3sgr1d5unie68d2qjcifjoolt5f.apps.googleusercontent.com
