export const DRIVER_QUICK_ACTIONS = [
  { key: 'go_online', label: 'Go Online', type: 'go_online' },
  { key: 'resume_active_ride', label: 'Resume Active Ride', type: 'resume_active_ride' },
  { key: 'navigate_active_ride', label: 'Navigate Active Ride', type: 'navigate_active_ride' },
  { key: 'call_passenger', label: 'Call Passenger', type: 'call_passenger' },
  { key: 'sos', label: 'SOS', type: 'sos' },
  { key: 'withdraw', label: 'Withdraw Earnings', type: 'withdraw_earnings' },
  { key: 'support_contact', label: 'Contact Support', type: 'support_contact' },
  { key: 'subscription', label: 'Subscription & Dues', type: 'tab', tab: 'subscription' },
  { key: 'earnings_report', label: 'Earnings Report', type: 'earnings_report' },
  { key: 'profile', label: 'Profile', type: 'tab', tab: 'profile' },
  { key: 'documents', label: 'Documents', type: 'tab', tab: 'documents' },
  { key: 'vehicle', label: 'Vehicle', type: 'tab', tab: 'vehicle' },
  { key: 'notifications', label: 'Notifications', type: 'tab', tab: 'notifications' },
  { key: 'analytics', label: 'Analytics', type: 'tab', tab: 'analytics' },
  { key: 'reviews', label: 'Reviews', type: 'tab', tab: 'reviews' },
  { key: 'history', label: 'Ride History & Receipts', type: 'tab', tab: 'history' },
  { key: 'spin', label: 'Spin and Win', type: 'tab', tab: 'spin' },
  { key: 'fare', label: 'Fare Calculator', type: 'tab', tab: 'fare' },
  { key: 'blocked', label: 'Blocked Passengers', type: 'tab', tab: 'blocked' },
  { key: 'trust', label: 'Trust and KYC', type: 'tab', tab: 'trust' },
  { key: 'safety', label: 'Safety Card', type: 'tab', tab: 'safety' },
];
